factory: form
name: settings
props:
    action: context.form_action
    class: ajax
widgets:
- groups_dn:
    factory: field:label:error:text
    value: expr:context.model.attrs.groups_dn
    props:
        label: Groups container DN
        required: No Groups DN defined
- groups_scope:
    factory: field:label:select
    value: expr:context.model.attrs.groups_scope
    props:
        label: Groups search scope
        vocabulary: expr:context.scope_vocab
- groups_query:
    factory: field:label:text
    value: expr:context.model.attrs.groups_query
    props:
        label: Groups search query filter
- groups_object_classes:
    factory: field:label:text
    value: expr:u', '.join(context.model.attrs.get('groups_object_classes', []))
    props:
        label: Object classes for Group creation
- groups_aliases_attrmap:
    factory: field:label:error:dict
    value: expr:context.groups_aliases_attrmap
    props:
        label: Group attribute aliases
        required: Group attribute aliases values are mandatory
        static: True
        head:
            key: Reserved key
            value: LDAP attr name
- groups_form_attrmap:
    factory: field:label:dict
    value: expr:context.model.attrs.groups_form_attrmap
    props:
        label: Group form attributes
        head:
            key: LDAP attr name
            value: Form label
- groups_relation:
    factory: field:label:text
    value: expr:context.model.attrs.groups_relation
    props:
        label: Group-member-relation
- groups_listing_columns:
    factory: field:label:dict
    value: expr:context.groups_listing_columns
    props:
        label: Column configuration for groups listings
        required: Column configuration for group listings value is mandatory
        static: True
        head:
            key: Listing Column
            value: LDAP Attribute
- groups_listing_default_column:
    factory: field:label:select
    value: expr:context.groups_listing_default_column
    props:
        label: Groups listing default columns
        vocabulary: expr:context.sort_column_vocab
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: Save